const questions = [
  {
    "topic": "Hemoglobin & Proteins",
    "question": "A young man has recurrent severe pain after vigorous exercise, anemia, and elongated “sausage-shaped” red blood cells. What underlying cause explains the change in cell shape?",
    "choices": [
      "Increased ionic interactions between Hb molecules in the oxygenated state",
      "Increased ionic interactions between Hb molecules in the deoxygenated state",
      "Increased hydrophobic interactions between Hb molecules in the oxygenated state",
      "Increased hydrophobic interactions between Hb molecules in the deoxygenated state",
      "Increased phosphorylation of Hb molecules in the oxygenated state"
    ],
    "answer": 3,
    "explanation": "Sickle cell disease is caused by HbS polymerization when deoxygenated. The mutation creates hydrophobic interactions between hemoglobin molecules."
  },
  {
    "topic": "Signal Transduction",
    "question": "Protein kinases phosphorylate proteins only at certain hydroxyl groups on amino acid side chains. Which amino acids can be substrates?",
    "choices": [
      "Aspartate, glutamate, and serine",
      "Serine, threonine, and tyrosine",
      "Threonine, phenylalanine, and arginine",
      "Lysine, arginine, and proline",
      "Alanine, asparagine, and serine"
    ],
    "answer": 1,
    "explanation": "Serine, threonine, and tyrosine contain hydroxyl groups commonly phosphorylated by kinases."
  },
  {
    "topic": "Endocrine",
    "question": "Some cells secrete chemicals into extracellular fluid that act on cells in the same tissue. What type of regulation is this?",
    "choices": [
      "Endocrine",
      "Neuroendocrine",
      "Neural",
      "Paracrine",
      "Autocrine"
    ],
    "answer": 3,
    "explanation": "Paracrine signaling acts locally on nearby cells in the same tissue."
  },
  {
    "topic": "Endocrine",
    "question": "Which statement about peptide or protein hormones is usually true?",
    "choices": [
      "They have longer half-lives than steroid hormones",
      "They have receptors on the cell membrane",
      "They have a slower onset than steroid and thyroid hormones",
      "They are not stored in endocrine-producing glands"
    ],
    "answer": 1,
    "explanation": "Peptide/protein hormones are water-soluble and usually bind cell-surface receptors."
  },
  {
    "topic": "Enzymes",
    "question": "Which of the following is a general property of catalysts?",
    "choices": [
      "They act as structural elements of the body",
      "They become covalently modified as part of every reaction cycle",
      "They must be broken down to amino acids after each cycle",
      "They remain unchanged at the completion of each reaction cycle"
    ],
    "answer": 3,
    "explanation": "Catalysts speed reactions and are regenerated by the end of the cycle."
  },
  {
    "topic": "Enzymes",
    "question": "If an enzyme catalyst is added to a reaction, which energy diagram parameter changes to increase reaction rate?",
    "choices": [
      "A",
      "B",
      "C",
      "D",
      "E"
    ],
    "answer": 2,
    "explanation": "The activation energy decreases. In the diagram, this was labeled C."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Why is ethanol used to treat toxic methanol ingestion?",
    "choices": [
      "Ethanol is a noncompetitive inhibitor",
      "Ethanol is a structural analog and competes with methanol for the active site",
      "Ethanol alters Vmax for methanol oxidation",
      "Ethanol inhibits regardless of methanol concentration",
      "Ethanol has a higher Km and higher affinity than methanol"
    ],
    "answer": 1,
    "explanation": "Ethanol competes with methanol for alcohol dehydrogenase, reducing formaldehyde production."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Acetazolamide binds near the active site of carbonic anhydrase. Substrate can still bind and be converted, but overall enzyme activity decreases. What happens?",
    "choices": [
      "Apparent Km increases",
      "Apparent Km decreases",
      "Vmax increases",
      "Vmax decreases",
      "Km and Vmax both decrease"
    ],
    "answer": 3,
    "explanation": "This describes noncompetitive/allosteric inhibition: Vmax decreases while Km is usually unchanged."
  },
  {
    "topic": "Abdominal Anatomy",
    "question": "Which structure marks the superior boundary of the abdominal cavity and assists in respiration?",
    "choices": [
      "Pelvic inlet",
      "Rectus abdominis",
      "Diaphragm",
      "Subcostal line"
    ],
    "answer": 2,
    "explanation": "The diaphragm separates the thoracic and abdominal cavities and drives respiration."
  },
  {
    "topic": "Abdominal Anatomy",
    "question": "What horizontal line passes through the iliac tubercles and helps define the lower boundary of the middle abdominal region?",
    "choices": [
      "Subcostal line",
      "Transtubercular line",
      "Midclavicular line",
      "Umbilical line"
    ],
    "answer": 1,
    "explanation": "The transtubercular line passes through the iliac tubercles."
  },
  {
    "topic": "Abdominal Anatomy",
    "question": "Which abdominal quadrant contains the liver and gallbladder?",
    "choices": [
      "Left Upper Quadrant",
      "Right Upper Quadrant",
      "Right Lower Quadrant",
      "Left Lower Quadrant"
    ],
    "answer": 1,
    "explanation": "The liver and gallbladder are in the right upper quadrant."
  },
  {
    "topic": "Abdominal Anatomy",
    "question": "Which abdominal region is associated with stomach and pancreas-related symptoms such as gastritis or pancreatitis?",
    "choices": [
      "Umbilical region",
      "Right hypochondriac region",
      "Epigastric region",
      "Hypogastric region"
    ],
    "answer": 2,
    "explanation": "The epigastric region overlies the stomach and pancreas."
  },
  {
    "topic": "GI Physiology",
    "question": "What is the main function of the small intestine?",
    "choices": [
      "Detoxifying blood and storing nutrients",
      "Producing insulin and digestive enzymes",
      "Absorbing water and forming feces",
      "Digesting food and absorbing nutrients"
    ],
    "answer": 3,
    "explanation": "Most digestion and nutrient absorption occurs in the small intestine."
  },
  {
    "topic": "Membrane Potential",
    "question": "Which statement about ionic concentrations at normal resting membrane potential is correct?",
    "choices": [
      "Higher sodium and potassium, lower chloride inside",
      "Lower sodium, potassium, and chloride inside",
      "Lower sodium and chloride, higher potassium inside",
      "Higher sodium, potassium, and chloride inside",
      "Lower sodium, higher potassium and chloride inside"
    ],
    "answer": 2,
    "explanation": "Inside neurons: high K+, low Na+, and generally lower Cl− compared with outside."
  },
  {
    "topic": "Nernst Equation",
    "question": "If extracellular K+ = 14 mM and intracellular K+ = 140 mM, membrane permeable only to K+, approximate Nernst potential?",
    "choices": [
      "-60 mV",
      "+60 mV",
      "-89 mV",
      "+89 mV",
      "-100 mV",
      "+100 mV"
    ],
    "answer": 0,
    "explanation": "A 10-fold K+ gradient gives approximately -60 mV at body temperature."
  },
  {
    "topic": "Protein Structure",
    "question": "Which component of a water-soluble globular protein is most likely in the center of the molecule?",
    "choices": [
      "Glutamate side chain",
      "Histidine side chain",
      "Phenylalanine side chain",
      "Phosphate on serine",
      "Oligosaccharide on asparagine"
    ],
    "answer": 2,
    "explanation": "Phenylalanine is hydrophobic and tends to be buried inside proteins."
  },
  {
    "topic": "Protein Structure",
    "question": "Which surface amino acid change would most likely increase hemoglobin water solubility?",
    "choices": [
      "Arg → Lys",
      "Leu → Phe",
      "Gln → Ser",
      "Ala → Asn",
      "Ser → Ala"
    ],
    "answer": 3,
    "explanation": "Ala is hydrophobic; Asn is polar, increasing solubility."
  },
  {
    "topic": "Amino Acids",
    "question": "What is the smallest amino acid?",
    "choices": [
      "Lysine",
      "Glycine",
      "Alanine",
      "Serine",
      "Proline"
    ],
    "answer": 1,
    "explanation": "Glycine’s side chain is a single hydrogen."
  },
  {
    "topic": "Amino Acids",
    "question": "Which amino acids are sulfur-containing?",
    "choices": [
      "Just cysteine",
      "Serine and threonine",
      "Methionine and threonine",
      "Cysteine and methionine",
      "Arginine and lysine"
    ],
    "answer": 3,
    "explanation": "Cysteine and methionine are the standard sulfur-containing amino acids."
  },
  {
    "topic": "Protein Structure",
    "question": "Which amino acid is considered a helix breaker?",
    "choices": [
      "Alanine",
      "Glycine",
      "Phenylalanine",
      "Proline",
      "Methionine"
    ],
    "answer": 3,
    "explanation": "Proline’s rigid ring disrupts alpha-helices."
  },
  {
    "topic": "Protein Structure",
    "question": "Most secondary structures form mainly to satisfy which interaction?",
    "choices": [
      "Hydrophobic interactions",
      "Van der Waals forces",
      "Ionic bonding",
      "Disulfide bonding",
      "Hydrogen bonding"
    ],
    "answer": 4,
    "explanation": "Alpha-helices and beta-sheets are stabilized by backbone hydrogen bonds."
  },
  {
    "topic": "Membrane Proteins",
    "question": "Porins contain what characteristic domain structure?",
    "choices": [
      "Transmembrane alpha helix",
      "7-transmembrane helical structure",
      "IgG fold",
      "Beta-barrel",
      "Globin fold"
    ],
    "answer": 3,
    "explanation": "Porins are beta-barrel membrane proteins."
  },
  {
    "topic": "Protein Structure",
    "question": "Which protein does not have quaternary structure?",
    "choices": [
      "Myoglobin",
      "Hemoglobin",
      "IgG",
      "Superoxide dismutase",
      "Collagen"
    ],
    "answer": 0,
    "explanation": "Myoglobin is a single polypeptide; the others have multiple subunits/chains."
  },
  {
    "topic": "Protein Structure",
    "question": "Disulfide bonds principally stabilize what level of protein structure?",
    "choices": [
      "Primary",
      "Secondary",
      "Tertiary",
      "Quaternary",
      "Macromolecular assembly"
    ],
    "answer": 2,
    "explanation": "Disulfide bonds stabilize tertiary structure by linking parts of the same polypeptide."
  },
  {
    "topic": "Protein Structure",
    "question": "Ionic bonds occur in proteins where and how often?",
    "choices": [
      "They are a major stabilizing force",
      "They often occur on the surface",
      "They occur in all protein cores",
      "They occur occasionally in the interior",
      "They are never found"
    ],
    "answer": 3,
    "explanation": "Internal salt bridges occur occasionally and can aid specificity or stability."
  },
  {
    "topic": "Endocrine",
    "question": "Why do endocrine functions remain intact after spinal cord injury causing paralysis and loss of reflexes below lesion?",
    "choices": [
      "Endocrine regulation depends on local neural inputs",
      "Endocrine signaling uses electrical synapses",
      "Endocrine control operates independently of action potentials and neural circuits",
      "Hormones pass through the spinal cord",
      "Motor neurons control all glands"
    ],
    "answer": 2,
    "explanation": "Hormones travel in blood and do not require spinal action potentials to reach targets."
  },
  {
    "topic": "Endocrine",
    "question": "A hormone synthesized on demand, not stored, diffuses into target cells, and binds intracellular receptors is classified as:",
    "choices": [
      "Peptide hormone",
      "Steroid hormone",
      "Protein hormone",
      "Amine hormone"
    ],
    "answer": 1,
    "explanation": "Steroids are lipid-soluble, made from cholesterol, and bind intracellular receptors."
  },
  {
    "topic": "Endocrine",
    "question": "Compared to insulin, what distinguishes cortisol’s hormonal class?",
    "choices": [
      "Binds surface receptors",
      "Stored in vesicles",
      "Synthesized from cholesterol",
      "Cleared rapidly by kidney"
    ],
    "answer": 2,
    "explanation": "Cortisol is a steroid hormone synthesized from cholesterol."
  },
  {
    "topic": "Endocrine",
    "question": "If a chemical agent is produced by a cell and acts on that same cell, the effect is:",
    "choices": [
      "Endocrine",
      "Paracrine",
      "Autocrine",
      "Neurocrine",
      "Neuroendocrine"
    ],
    "answer": 2,
    "explanation": "Autocrine signaling acts on the same cell that released the signal."
  },
  {
    "topic": "Endocrine",
    "question": "Which hormone is not stored in its endocrine-producing gland?",
    "choices": [
      "T4",
      "PTH",
      "Aldosterone",
      "ACTH",
      "Insulin"
    ],
    "answer": 2,
    "explanation": "Steroid hormones like aldosterone are synthesized on demand and not stored much."
  },
  {
    "topic": "Endocrine",
    "question": "Which characteristic distinguishes lipid-soluble hormones from water-soluble hormones?",
    "choices": [
      "Stored in vesicles",
      "Bind surface receptors",
      "Typically have longer half-lives",
      "Require second messengers",
      "More rapidly degraded in plasma"
    ],
    "answer": 2,
    "explanation": "Lipid-soluble hormones bind carrier proteins and usually last longer."
  },
  {
    "topic": "Endocrine",
    "question": "Drug receptors for steroids are most likely present in which cellular location?",
    "choices": [
      "Nuclear membrane",
      "Cell cytoplasm",
      "Cell membrane",
      "Mitochondria",
      "Endoplasmic reticulum"
    ],
    "answer": 1,
    "explanation": "Steroid receptors are intracellular, commonly cytosolic or nuclear."
  },
  {
    "topic": "Endocrine",
    "question": "Which is expected for a peptide hormone?",
    "choices": [
      "Long plasma half-life and nuclear receptor",
      "Rapid onset and cell-surface receptor binding",
      "Carrier proteins required",
      "Passive diffusion through membranes",
      "Synthesized from cholesterol"
    ],
    "answer": 1,
    "explanation": "Peptides act through membrane receptors and often have rapid effects."
  },
  {
    "topic": "Endocrine",
    "question": "GH levels are higher at midnight than noon. Which endocrine control system explains this?",
    "choices": [
      "Negative feedback",
      "Positive feedback",
      "Stress-related",
      "Exercise-related",
      "Circadian"
    ],
    "answer": 4,
    "explanation": "Growth hormone secretion follows circadian rhythms."
  },
  {
    "topic": "Endocrine",
    "question": "A rise in blood calcium decreases PTH secretion. This is:",
    "choices": [
      "Positive feedback",
      "Paracrine inhibition",
      "Feedforward regulation",
      "Negative feedback",
      "Autocrine signaling"
    ],
    "answer": 3,
    "explanation": "Negative feedback reduces hormone secretion when the regulated variable rises."
  },
  {
    "topic": "Endocrine",
    "question": "What directly decreases with increased plasma protein binding of a hormone?",
    "choices": [
      "Hormone half-life",
      "Total hormone concentration",
      "Free active hormone levels",
      "Receptor synthesis",
      "Hormone affinity"
    ],
    "answer": 2,
    "explanation": "Only unbound hormone is biologically active."
  },
  {
    "topic": "Endocrine",
    "question": "Which hypothalamic-pituitary pair is incorrect? A Somatostatin ↓GH, B Dopamine ↑Prolactin, C GnRH ↑LH, D TRH ↑TSH, E CRH ↑ACTH",
    "choices": [
      "A",
      "B",
      "C",
      "D",
      "E"
    ],
    "answer": 1,
    "explanation": "Dopamine inhibits prolactin; it does not stimulate it."
  },
  {
    "topic": "Enzymes",
    "question": "Thermus aquaticus DNA polymerase from hot springs likely has what temperature optimum?",
    "choices": [
      "10°C",
      "25°C",
      "37°C",
      "50°C",
      "80°C"
    ],
    "answer": 4,
    "explanation": "Thermophilic enzymes are adapted to high temperatures."
  },
  {
    "topic": "Enzymes",
    "question": "Match lipase pH optima: lingual, gastric, pancreatic.",
    "choices": [
      "4.5–5.4; 3–6; 8–9",
      "8–9; 4.5–5.4; 3–6",
      "3–6; 8–9; 4.5–5.4",
      "4.5–5.4; 8–9; 3–6",
      "3–6; 4.5–5.4; 8–9"
    ],
    "answer": 0,
    "explanation": "Lingual and gastric lipases work in acidic environments; pancreatic lipase works in alkaline small intestine."
  },
  {
    "topic": "Cofactors",
    "question": "Which cofactor acts as a prosthetic group?",
    "choices": [
      "NAD+",
      "FAD",
      "Coenzyme A",
      "THF"
    ],
    "answer": 1,
    "explanation": "FAD is often tightly bound to enzymes; NAD+, CoA, and THF usually act as cosubstrates."
  },
  {
    "topic": "Enzymes",
    "question": "Which best represents induced-fit binding?",
    "choices": [
      "Glucose binding to hexokinase",
      "Lysine side chain binding trypsin pocket",
      "Collagen assembling into strands",
      "Actin polymerizing"
    ],
    "answer": 0,
    "explanation": "Hexokinase changes shape around glucose, a classic induced-fit example."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Which statement regarding enzyme inhibition is correct?",
    "choices": [
      "Substrate competes with enzyme for inhibitor protein",
      "Substrate and inhibitor compete for active site on enzyme",
      "Noncompetitive inhibition is overcome by lots of substrate",
      "Noncompetitive inhibitors often bind irreversibly"
    ],
    "answer": 1,
    "explanation": "Competitive inhibitors compete with substrate for the enzyme active site."
  },
  {
    "topic": "Enzyme Kinetics",
    "question": "Substrate concentration dependencies of two enzymes are best compared using which parameter?",
    "choices": [
      "Rate of product formation",
      "Optimum pH",
      "KM value",
      "Molecular weight"
    ],
    "answer": 2,
    "explanation": "KM reflects substrate concentration needed to reach half Vmax."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Line A is control and line B with inhibitor shows same Vmax but increased Km. What inhibition is observed?",
    "choices": [
      "Competitive",
      "Noncompetitive",
      "Uncompetitive",
      "Suicide"
    ],
    "answer": 0,
    "explanation": "Competitive inhibition increases apparent Km but Vmax can be reached."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "For the inhibitor in the graph showing competitive inhibition, where does it bind?",
    "choices": [
      "Outer surface",
      "Active site",
      "Allosteric regulatory site",
      "Upstream enzyme",
      "Kinase"
    ],
    "answer": 1,
    "explanation": "Competitive inhibitors bind the active site."
  },
  {
    "topic": "Enzyme Kinetics",
    "question": "Hexokinase KM is 500 µM. If intracellular glucose is 5 mM, approximate velocity relative to Vmax?",
    "choices": [
      "¼ Vmax",
      "½ Vmax",
      "¾ Vmax",
      "9/10 Vmax",
      "Vmax"
    ],
    "answer": 3,
    "explanation": "5 mM is 10× KM, so v = 10/11 Vmax ≈ 0.91 Vmax."
  },
  {
    "topic": "Enzyme Kinetics",
    "question": "Velocity at 3 mM substrate is 25% of Vmax. What is KM?",
    "choices": [
      "0.75 mM",
      "3 mM",
      "6 mM",
      "9 mM",
      "12 mM",
      "20 mM"
    ],
    "answer": 3,
    "explanation": "0.25 = S/(Km+S). Km = 3S = 9 mM."
  },
  {
    "topic": "Enzyme Kinetics",
    "question": "With inhibitor: Vmax = 6 units/min/mg, KM = 1.25 µM. At [S] = 2.5 µM, what is velocity?",
    "choices": [
      "1",
      "1.25",
      "2",
      "2.5",
      "4",
      "5",
      "6"
    ],
    "answer": 4,
    "explanation": "v = Vmax[S]/(Km+[S]) = 6×2.5/(1.25+2.5)=4."
  },
  {
    "topic": "Allosteric Regulation",
    "question": "Allosteric ligands can modify which kinetic parameters?",
    "choices": [
      "KM",
      "Vmax",
      "KM and Vmax",
      "KI"
    ],
    "answer": 2,
    "explanation": "Allosteric binding can change affinity and/or catalytic activity."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "For alcohol dehydrogenase, what is the relationship between methanol and ethanol?",
    "choices": [
      "Ethanol substrate; methanol allosteric inhibitor",
      "Ethanol and methanol are competitive",
      "They are cosubstrates",
      "Both allosterically affect activity",
      "Both are substrates but neither affects the other"
    ],
    "answer": 1,
    "explanation": "They compete for alcohol dehydrogenase."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Statins compete with which compound on HMG-CoA reductase?",
    "choices": [
      "Acetyl-CoA",
      "Cholesterol",
      "Coenzyme A",
      "HMG-CoA",
      "Malonyl-CoA"
    ],
    "answer": 3,
    "explanation": "Statins competitively inhibit HMG-CoA reductase by resembling HMG-CoA."
  },
  {
    "topic": "Allosteric Regulation",
    "question": "ADP activates hexokinase while glucose-6-phosphate inhibits it. Best explanation?",
    "choices": [
      "They counteract each other",
      "G6P inhibits as accumulation sensor, ADP activates as energy-state sensor",
      "ADP affinity too low to matter",
      "Both sites are vestigial"
    ],
    "answer": 1,
    "explanation": "G6P signals product buildup; ADP signals low energy and need for glycolysis."
  },
  {
    "topic": "Membrane Potential",
    "question": "What primary ion establishes resting membrane potential in most cells?",
    "choices": [
      "Sodium (Na+)",
      "Potassium (K+)",
      "Calcium (Ca2+)",
      "Chloride (Cl−)",
      "Bicarbonate (HCO3−)"
    ],
    "answer": 1,
    "explanation": "Resting membrane potential is mostly determined by K+ leak conductance."
  },
  {
    "topic": "Membrane Potential",
    "question": "What does the Na+/K+ ATPase pump do?",
    "choices": [
      "Passive diffusion",
      "Generates action potentials directly",
      "Maintains gradients by pumping Na+ out and K+ in",
      "Allows free ion movement",
      "Pumps K+ out and Na+ in"
    ],
    "answer": 2,
    "explanation": "It pumps 3 Na+ out and 2 K+ in using ATP."
  },
  {
    "topic": "Membrane Potential",
    "question": "Which condition makes resting membrane potential more negative?",
    "choices": [
      "Increased Na+ permeability",
      "Increased K+ permeability",
      "Decreased Cl− permeability",
      "Increased intracellular Na+",
      "Increased Ca2+ permeability"
    ],
    "answer": 1,
    "explanation": "More K+ efflux makes the inside more negative."
  },
  {
    "topic": "Nernst Equation",
    "question": "What does the Nernst equation calculate?",
    "choices": [
      "Action potential amplitude",
      "Ion channel opening rate",
      "Equilibrium potential of an ion across a membrane",
      "Membrane resistance",
      "Time constant"
    ],
    "answer": 2,
    "explanation": "The Nernst equation calculates the voltage balancing an ion gradient."
  },
  {
    "topic": "Nernst Equation",
    "question": "Approximate EK if [K+]out = 5 mM and [K+]in = 150 mM?",
    "choices": [
      "+90 mV",
      "+60 mV",
      "0 mV",
      "−90 mV",
      "−30 mV",
      "−60 mV"
    ],
    "answer": 3,
    "explanation": "A 30-fold gradient gives about −90 mV."
  },
  {
    "topic": "Nernst Equation",
    "question": "[K+]in = 100 mM, [K+]out = 10 mM. EK ≈ ? If RMP = −70 mV, direction/effect?",
    "choices": [
      "EK≈−58 mV; K+ into cell; depolarize",
      "EK≈−88 mV; K+ into cell; hyperpolarize",
      "EK≈−58 mV; K+ out; hyperpolarize",
      "EK≈−58 mV; K+ out; depolarize",
      "EK≈−70 mV; no net movement"
    ],
    "answer": 0,
    "explanation": "Vm is more negative than EK, so K+ enters and depolarizes toward −58 mV."
  },
  {
    "topic": "Membrane Potential",
    "question": "If Vm = −90 mV and ECl = −60 mV, which direction will Cl− move if channels open?",
    "choices": [
      "Out of the cell",
      "Into the cell",
      "No net movement",
      "Depends on sodium cotransport",
      "Not enough information"
    ],
    "answer": 0,
    "explanation": "Cl− exits to move Vm toward ECl."
  },
  {
    "topic": "Membrane Potential",
    "question": "In skeletal muscle at rest, which ion is closest to its Nernst equilibrium potential?",
    "choices": [
      "Na+",
      "Cl−",
      "K+",
      "Ca2+"
    ],
    "answer": 2,
    "explanation": "Resting potential is close to EK, around −90 mV."
  },
  {
    "topic": "Nernst Equation",
    "question": "[K+]out = 2.5 mM and [K+]in = 140 mM. Approximate EK?",
    "choices": [
      "−80 mV",
      "−85 mV",
      "−92 mV",
      "−105 mV",
      "+107 mV",
      "+95 mV",
      "+88 mV"
    ],
    "answer": 3,
    "explanation": "Hypokalemia makes EK more negative, around −105 mV."
  },
  {
    "topic": "Nernst Equation",
    "question": "[K+]out = 7.5 mM and [K+]in = 120 mM. Approximate EK?",
    "choices": [
      "−80 mV",
      "−72 mV",
      "−65 mV",
      "−60 mV",
      "−52 mV"
    ],
    "answer": 1,
    "explanation": "Hyperkalemia makes EK less negative, around −72 mV."
  },
  {
    "topic": "Action Potentials",
    "question": "Which mechanism returns membrane potential toward resting value at the peak of an action potential?",
    "choices": [
      "Opening of voltage-gated K+ channels",
      "Opening of voltage-gated Na+ channels",
      "Opening of voltage-gated Ca2+ channels",
      "Opening ligand-gated K+ channels",
      "None"
    ],
    "answer": 0,
    "explanation": "Voltage-gated K+ channels open, K+ leaves, and the membrane repolarizes."
  },
  {
    "topic": "Action Potentials",
    "question": "What change causes rapid neuronal depolarization?",
    "choices": [
      "Opening K+ channels",
      "Closure K+ channels",
      "Inactivation K+ channels",
      "Opening Na+ channels",
      "Closure Na+ channels"
    ],
    "answer": 3,
    "explanation": "Voltage-gated Na+ channels open rapidly, causing Na+ influx."
  },
  {
    "topic": "Action Potentials",
    "question": "Opening voltage-gated K+ channels is responsible for which part of the action potential?",
    "choices": [
      "Depolarization",
      "Repolarization",
      "Resting stage",
      "Overshoot"
    ],
    "answer": 1,
    "explanation": "K+ efflux repolarizes the membrane."
  },
  {
    "topic": "Drugs & Toxins",
    "question": "At low concentrations, what direct effect does lidocaine have on resting membrane potential?",
    "choices": [
      "Significant hyperpolarization",
      "Significant depolarization",
      "Minimal direct effect",
      "Hyperpolarizes by increasing K+ permeability",
      "Increases Na+/K+ ATPase"
    ],
    "answer": 2,
    "explanation": "RMP depends mostly on K+ leak channels; lidocaine blocks voltage-gated Na+ channels."
  },
  {
    "topic": "Drugs & Toxins",
    "question": "Tetrodotoxin causes weakness and respiratory paralysis by directly causing:",
    "choices": [
      "Increased K+ permeability",
      "Prolonged repolarization",
      "Blockage of voltage-sensitive Na+ channels",
      "Blockage of voltage-sensitive K+ channels",
      "Hyperpolarization of RMP"
    ],
    "answer": 2,
    "explanation": "TTX blocks voltage-gated sodium channels, preventing action potentials."
  },
  {
    "topic": "Graded Potentials",
    "question": "Which feature is unique to graded potentials but not action potentials?",
    "choices": [
      "Triggered by threshold",
      "All-or-none response",
      "Decays over distance",
      "Involves voltage-gated channels",
      "Duration is constant"
    ],
    "answer": 2,
    "explanation": "Graded potentials decrease with distance; action potentials regenerate."
  },
  {
    "topic": "Action Potentials",
    "question": "What ion movement primarily causes repolarization?",
    "choices": [
      "Na+ influx",
      "K+ efflux",
      "Ca2+ influx",
      "Cl− efflux",
      "Na+/K+ pump"
    ],
    "answer": 1,
    "explanation": "K+ leaving the cell makes the inside more negative again."
  },
  {
    "topic": "Action Potentials",
    "question": "During the absolute refractory period, what is the status of voltage-gated Na+ channel gates?",
    "choices": [
      "Both gates open",
      "Activation gate open, inactivation gate closed",
      "Both gates closed",
      "Activation gate closed, inactivation gate open",
      "Recycled to resting"
    ],
    "answer": 1,
    "explanation": "The Na+ channel is inactivated, so another action potential cannot be generated."
  },
  {
    "topic": "Action Potentials",
    "question": "Which is essential for action potential initiation and propagation?",
    "choices": [
      "Ligand-gated Na+ opening",
      "Gradual depolarization without threshold",
      "Activation of voltage-gated Na+ channels",
      "Inactivation of voltage-gated K+ channels",
      "Passive Na+ leak"
    ],
    "answer": 2,
    "explanation": "Voltage-gated Na+ channel activation produces regenerative depolarization."
  },
  {
    "topic": "Drugs & Toxins",
    "question": "TEA causes action potentials to occur but repolarization is prolonged. Why?",
    "choices": [
      "TEA inhibits sodium influx",
      "TEA prevents ligand-gated chloride opening",
      "TEA blocks voltage-gated K+ channels, slowing K+ efflux",
      "TEA enhances Na+/K+ pump",
      "TEA causes complete depolarization"
    ],
    "answer": 2,
    "explanation": "Blocking K+ channels slows repolarization."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "A competitive inhibitor binds to:",
    "choices": [
      "An allosteric site",
      "The active site",
      "The substrate",
      "The product"
    ],
    "answer": 1,
    "explanation": "Competitive inhibitors resemble the substrate and compete for the enzyme active site."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Which type of inhibition can be overcome by increasing substrate concentration?",
    "choices": [
      "Competitive",
      "Noncompetitive",
      "Uncompetitive",
      "Suicide"
    ],
    "answer": 0,
    "explanation": "More substrate can outcompete a competitive inhibitor for the active site."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "A competitive inhibitor causes which kinetic change?",
    "choices": [
      "Increased Km, unchanged Vmax",
      "Increased Km, decreased Vmax",
      "Decreased Km, unchanged Vmax",
      "Decreased Km, decreased Vmax"
    ],
    "answer": 0,
    "explanation": "Competitive inhibition increases apparent Km because more substrate is needed, but Vmax is unchanged."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "A pure noncompetitive inhibitor causes which kinetic change?",
    "choices": [
      "Increased Km, unchanged Vmax",
      "Unchanged Km, decreased Vmax",
      "Decreased Km, decreased Vmax",
      "Increased Km, increased Vmax"
    ],
    "answer": 1,
    "explanation": "Pure noncompetitive inhibition decreases Vmax but leaves Km unchanged."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "A noncompetitive inhibitor typically binds to:",
    "choices": [
      "The active site",
      "An allosteric site",
      "The product-binding site",
      "ATP only"
    ],
    "answer": 1,
    "explanation": "Noncompetitive inhibitors bind away from the active site and reduce catalytic activity."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Increasing substrate concentration has what effect on noncompetitive inhibition?",
    "choices": [
      "Completely reverses inhibition",
      "Partially reverses inhibition",
      "Does not reverse inhibition",
      "Increases inhibition"
    ],
    "answer": 2,
    "explanation": "Noncompetitive inhibition cannot be overcome by adding more substrate because the inhibitor does not compete for the active site."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "An uncompetitive inhibitor binds to:",
    "choices": [
      "Free enzyme only",
      "The enzyme-substrate complex only",
      "The active site only",
      "The product only"
    ],
    "answer": 1,
    "explanation": "Uncompetitive inhibitors bind only after substrate has bound, forming an enzyme-substrate-inhibitor complex."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Uncompetitive inhibition causes which kinetic change?",
    "choices": [
      "Increased Km and increased Vmax",
      "Increased Km and decreased Vmax",
      "Decreased Km and decreased Vmax",
      "Decreased Km and increased Vmax"
    ],
    "answer": 2,
    "explanation": "Uncompetitive inhibition decreases both Km and Vmax."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Which inhibition type becomes more effective at high substrate concentrations?",
    "choices": [
      "Competitive",
      "Noncompetitive",
      "Uncompetitive",
      "Reversible"
    ],
    "answer": 2,
    "explanation": "High substrate concentration creates more enzyme-substrate complexes, giving uncompetitive inhibitors more targets."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "A suicide inhibitor is best described as an inhibitor that:",
    "choices": [
      "Reversibly binds the active site",
      "Binds only an allosteric site",
      "Is converted by the enzyme into a reactive molecule that permanently inactivates the enzyme",
      "Only inhibits at high substrate concentrations"
    ],
    "answer": 2,
    "explanation": "A suicide inhibitor is mechanism-based and causes irreversible enzyme inactivation."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Which of the following is a classic example of a suicide inhibitor?",
    "choices": [
      "Ethanol",
      "Methanol",
      "ATP",
      "Penicillin"
    ],
    "answer": 3,
    "explanation": "Penicillin irreversibly inhibits bacterial transpeptidase enzymes."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Which inhibitor type decreases Vmax but does not increase Km in the pure form?",
    "choices": [
      "Competitive",
      "Noncompetitive",
      "Uncompetitive",
      "Substrate"
    ],
    "answer": 1,
    "explanation": "Pure noncompetitive inhibition decreases Vmax while Km stays the same."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Methanol and ethanol compete for alcohol dehydrogenase. This is an example of:",
    "choices": [
      "Competitive inhibition",
      "Noncompetitive inhibition",
      "Uncompetitive inhibition",
      "Suicide inhibition"
    ],
    "answer": 0,
    "explanation": "They compete for the same active site on alcohol dehydrogenase."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Statins inhibit HMG-CoA reductase mainly by:",
    "choices": [
      "Competitive inhibition",
      "Noncompetitive inhibition",
      "Uncompetitive inhibition",
      "Suicide inhibition"
    ],
    "answer": 0,
    "explanation": "Statins resemble HMG-CoA and compete at the active site."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Which inhibitor type decreases both Km and Vmax?",
    "choices": [
      "Competitive",
      "Noncompetitive",
      "Uncompetitive",
      "Suicide"
    ],
    "answer": 2,
    "explanation": "Uncompetitive inhibition lowers both Km and Vmax."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Which inhibitor type increases apparent Km because the enzyme appears to have lower substrate affinity?",
    "choices": [
      "Competitive",
      "Pure noncompetitive",
      "Uncompetitive",
      "Suicide"
    ],
    "answer": 0,
    "explanation": "Competitive inhibitors make it seem like more substrate is needed, increasing apparent Km."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Which inhibitor type is irreversible and often lowers the amount of functional enzyme available?",
    "choices": [
      "Competitive",
      "Uncompetitive",
      "Suicide",
      "Allosteric activator"
    ],
    "answer": 2,
    "explanation": "Suicide inhibitors permanently inactivate enzyme molecules, reducing active enzyme."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "A Lineweaver-Burk plot shows the same x-intercept but a higher y-intercept with inhibitor. Which inhibition is suggested?",
    "choices": [
      "Competitive",
      "Pure noncompetitive",
      "Uncompetitive",
      "No inhibition"
    ],
    "answer": 1,
    "explanation": "Same x-intercept means Km unchanged; higher y-intercept means 1/Vmax increased, so Vmax decreased."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "A Lineweaver-Burk plot shows parallel lines with inhibitor present. Which inhibition is suggested?",
    "choices": [
      "Competitive",
      "Noncompetitive",
      "Uncompetitive",
      "No inhibition"
    ],
    "answer": 2,
    "explanation": "Uncompetitive inhibition decreases both Km and Vmax proportionally, producing parallel Lineweaver-Burk lines."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "A Lineweaver-Burk plot shows the same y-intercept but a different x-intercept with inhibitor. Which inhibition is suggested?",
    "choices": [
      "Competitive",
      "Noncompetitive",
      "Uncompetitive",
      "Suicide"
    ],
    "answer": 0,
    "explanation": "Same y-intercept means Vmax unchanged; changed x-intercept reflects increased Km."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "A cell releases a chemical messenger that enters the bloodstream and affects cells in a distant organ. This is an example of:",
    "choices": [
      "Autocrine signaling",
      "Paracrine signaling",
      "Endocrine signaling",
      "Neuroendocrine signaling"
    ],
    "answer": 2,
    "explanation": "Endocrine signaling uses hormones that travel through the bloodstream to distant target organs."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "A hormone secreted by a cell binds to receptors on the same cell that released it. This is:",
    "choices": [
      "Endocrine",
      "Paracrine",
      "Autocrine",
      "Neuroendocrine"
    ],
    "answer": 2,
    "explanation": "Autocrine signaling means the signal acts on the same cell that released it. Auto = self."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "Nitric oxide released by endothelial cells causes nearby smooth muscle relaxation. This is:",
    "choices": [
      "Endocrine",
      "Paracrine",
      "Autocrine",
      "Neuroendocrine"
    ],
    "answer": 1,
    "explanation": "Paracrine signals act locally on nearby cells in the same tissue."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "ADH, also called vasopressin, released from the posterior pituitary is an example of:",
    "choices": [
      "Paracrine signaling",
      "Autocrine signaling",
      "Neuroendocrine signaling",
      "Juxtacrine signaling"
    ],
    "answer": 2,
    "explanation": "ADH is released by neurons into the bloodstream, making it neuroendocrine signaling."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "Which signaling mechanism is generally fastest because it acts locally rather than traveling through the bloodstream?",
    "choices": [
      "Endocrine",
      "Neuroendocrine",
      "Paracrine",
      "Long-distance hormonal signaling"
    ],
    "answer": 2,
    "explanation": "Paracrine signaling is usually faster than endocrine signaling because it acts on nearby cells through local diffusion."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "Which signaling mechanism requires transport through the bloodstream to reach distant target cells?",
    "choices": [
      "Paracrine",
      "Autocrine",
      "Endocrine",
      "Juxtacrine"
    ],
    "answer": 2,
    "explanation": "Endocrine hormones are secreted into blood and travel to distant targets."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "Hypothalamic neurons release CRH into the hypophyseal portal circulation to affect the anterior pituitary. This is:",
    "choices": [
      "Endocrine",
      "Autocrine",
      "Paracrine",
      "Neuroendocrine"
    ],
    "answer": 3,
    "explanation": "Neuroendocrine signaling occurs when neurons release hormones into blood or portal circulation."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "A macrophage releases cytokines that influence neighboring immune cells. This is:",
    "choices": [
      "Endocrine",
      "Paracrine",
      "Autocrine",
      "Neuroendocrine"
    ],
    "answer": 1,
    "explanation": "Cytokines acting on nearby immune cells are an example of paracrine signaling."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "Interleukin-2 stimulates proliferation of the same T-cell that secreted it. This is:",
    "choices": [
      "Endocrine",
      "Paracrine",
      "Autocrine",
      "Neuroendocrine"
    ],
    "answer": 2,
    "explanation": "When a signal acts on the same cell that secreted it, it is autocrine signaling."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "Which best distinguishes endocrine signaling from paracrine signaling?",
    "choices": [
      "Endocrine signaling uses receptors",
      "Paracrine signaling uses receptors",
      "Endocrine signaling acts at distant sites via blood",
      "Paracrine signaling only occurs in the nervous system"
    ],
    "answer": 2,
    "explanation": "The key difference is distance and route: endocrine signals travel through blood to distant targets, while paracrine signals act locally."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "A neuron releases oxytocin into the bloodstream. This is:",
    "choices": [
      "Endocrine",
      "Autocrine",
      "Paracrine",
      "Neuroendocrine"
    ],
    "answer": 3,
    "explanation": "Neuroendocrine signaling is nerve cell secretion of hormones into blood."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "Which signaling type acts on neighboring cells without entering the systemic circulation?",
    "choices": [
      "Endocrine",
      "Paracrine",
      "Neuroendocrine",
      "Synaptic endocrine"
    ],
    "answer": 1,
    "explanation": "Paracrine signaling affects nearby cells and does not rely on systemic circulation."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "Which phrase best matches autocrine signaling?",
    "choices": [
      "Acts on itself",
      "Acts far away through blood",
      "Neuron releases hormone into blood",
      "Acts only through motor neurons"
    ],
    "answer": 0,
    "explanation": "Autocrine signaling means the cell responds to its own secreted chemical messenger."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "Which phrase best matches neuroendocrine signaling?",
    "choices": [
      "Cell acts on itself",
      "Neighboring cells communicate locally",
      "Neuron releases hormone into blood",
      "Hormone acts without receptors"
    ],
    "answer": 2,
    "explanation": "Neuroendocrine signaling occurs when neurons secrete hormones into the blood."
  },
  {
    "topic": "Endocrine Signaling",
    "question": "A local growth factor secreted by one cell stimulates nearby cells during wound healing. This is most likely:",
    "choices": [
      "Autocrine",
      "Paracrine",
      "Endocrine",
      "Neuroendocrine"
    ],
    "answer": 1,
    "explanation": "Local growth factors acting on nearby cells are usually paracrine signals."
  },
  {
    "topic": "Enzyme Kinetics",
    "question": "What is enzyme kinetics primarily used to study?",
    "choices": [
      "Enzyme structure determination",
      "Reaction rates of enzymes",
      "Enzyme distribution in tissues",
      "Genetic coding of enzymes",
      "Membrane transport functions"
    ],
    "answer": 1,
    "explanation": "Enzyme kinetics studies the reaction rates of enzyme-catalyzed reactions, helping scientists understand biocatalysis and develop drugs."
  },
  {
    "topic": "Enzyme Kinetics",
    "question": "How does increasing substrate concentration affect enzyme velocity initially?",
    "choices": [
      "Velocity immediately plateaus",
      "Velocity decreases proportionally",
      "Velocity increases proportionally",
      "Enzymes denature quickly",
      "Substrate inhibits velocity"
    ],
    "answer": 2,
    "explanation": "At low substrate concentrations, increasing substrate concentration causes enzyme velocity to increase proportionally because more active sites become occupied."
  },
  {
    "topic": "Enzyme Kinetics",
    "question": "What does Km represent in enzyme kinetics?",
    "choices": [
      "Maximum enzyme velocity",
      "Turnover number per enzyme",
      "Catalytic efficiency ratio",
      "Substrate concentration at half-Vmax",
      "Diffusion-limited efficiency"
    ],
    "answer": 3,
    "explanation": "Km is the substrate concentration required for reaction velocity to reach 1/2 Vmax. Low Km means high affinity; high Km means low affinity."
  },
  {
    "topic": "Enzyme Kinetics",
    "question": "What kinetic pattern indicates a two-substrate ping-pong mechanism on Lineweaver-Burk plots?",
    "choices": [
      "Intersecting lines at origin",
      "Parallel lines at varying substrate concentrations",
      "Intersecting lines off axis",
      "Single straight line plot",
      "Lines crossing at y-axis"
    ],
    "answer": 1,
    "explanation": "A ping-pong, or double-displacement, mechanism produces parallel lines on a Lineweaver-Burk plot. Ping-pong equals parallel lines."
  },
  {
    "topic": "Enzyme Inhibition",
    "question": "Which inhibition type decreases Vmax but keeps Km unchanged?",
    "choices": [
      "Competitive inhibition",
      "Uncompetitive inhibition",
      "Mixed inhibition",
      "Irreversible inhibition",
      "Noncompetitive inhibition"
    ],
    "answer": 4,
    "explanation": "Noncompetitive inhibitors bind equally well to the free enzyme and enzyme-substrate complex, causing decreased Vmax while Km remains unchanged."
  }
];